// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IotApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016115727_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IotApi.Models.AiAgent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("agent_code");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_name");

                    b.Property<string>("AsrModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("asr_model_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("IntentModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("intent_model_id");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("LlmModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("llm_model_id");

                    b.Property<string>("MemModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mem_model_id");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<string>("TtsModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tts_model_id");

                    b.Property<string>("TtsVoiceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tts_voice_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("VadModelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vad_model_id");

                    b.HasKey("Id");

                    b.ToTable("ai_agent");
                });

            modelBuilder.Entity("IotApi.Models.AiAgentTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("agent_code");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_name");

                    b.Property<string>("AsrModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("asr_model_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("IntentModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("intent_model_id");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("LlmModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("llm_model_id");

                    b.Property<string>("MemModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mem_model_id");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<string>("TtsModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tts_model_id");

                    b.Property<string>("TtsVoiceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tts_voice_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.Property<string>("VadModelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vad_model_id");

                    b.HasKey("Id");

                    b.ToTable("ai_agent_template");
                });

            modelBuilder.Entity("IotApi.Models.AiChatHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("agent_id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("device_id");

                    b.Property<int?>("MessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("message_count");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("ai_chat_history");
                });

            modelBuilder.Entity("IotApi.Models.AiChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("chat_id");

                    b.Property<int?>("CompletionMs")
                        .HasColumnType("integer")
                        .HasColumnName("completion_ms");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<int?>("PromptMs")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_ms");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<int?>("TotalMs")
                        .HasColumnType("integer")
                        .HasColumnName("total_ms");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("ai_chat_message");
                });

            modelBuilder.Entity("IotApi.Models.AiDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("agent_id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("alias");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("app_version");

                    b.Property<int?>("AutoUpdate")
                        .HasColumnType("integer")
                        .HasColumnName("auto_update");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("board");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connected_at");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mac_address");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("ai_device");
                });

            modelBuilder.Entity("IotApi.Models.AiModelConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_json");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("DocLink")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("doc_link");

                    b.Property<int?>("IsDefault")
                        .HasColumnType("integer")
                        .HasColumnName("is_default");

                    b.Property<int?>("IsEnabled")
                        .HasColumnType("integer")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_code");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("model_type");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remark");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.HasKey("Id");

                    b.ToTable("ai_model_config");
                });

            modelBuilder.Entity("IotApi.Models.AiModelProvider", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("Fields")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fields");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("model_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_code");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.HasKey("Id");

                    b.ToTable("ai_model_provider");
                });

            modelBuilder.Entity("IotApi.Models.AiOta", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("FirmwareName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("firmware_name");

                    b.Property<string>("FirmwarePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("firmware_path");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("ai_ota");
                });

            modelBuilder.Entity("IotApi.Models.AiTtsVoice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("languages");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remark");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<string>("TtsModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tts_model_id");

                    b.Property<string>("TtsVoice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tts_voice");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.Property<string>("VoiceDemo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("voice_demo");

                    b.HasKey("Id");

                    b.ToTable("ai_tts_voice");
                });

            modelBuilder.Entity("IotApi.Models.AiVoiceClone", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("TrainError")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("train_error");

                    b.Property<int?>("TrainStatus")
                        .HasColumnType("integer")
                        .HasColumnName("train_status");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("Voice")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("voice");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("voice_id");

                    b.HasKey("Id");

                    b.ToTable("ai_voice_clone");
                });

            modelBuilder.Entity("IotApi.Models.AiVoiceprint", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("agent_code");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("agent_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("embedding");

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("ai_voiceprint");
                });

            modelBuilder.Entity("IotApi.Models.SysDictData", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("DictLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dict_label");

                    b.Property<long>("DictTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("dict_type_id");

                    b.Property<string>("DictValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dict_value");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remark");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.HasKey("Id");

                    b.ToTable("sys_dict_data");
                });

            modelBuilder.Entity("IotApi.Models.SysDictType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("DictName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dict_name");

                    b.Property<string>("DictType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dict_type");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remark");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.HasKey("Id");

                    b.ToTable("sys_dict_type");
                });

            modelBuilder.Entity("IotApi.Models.SysParams", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("ParamCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("param_code");

                    b.Property<int?>("ParamType")
                        .HasColumnType("integer")
                        .HasColumnName("param_type");

                    b.Property<string>("ParamValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("param_value");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("remark");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.HasKey("Id");

                    b.ToTable("sys_params");
                });

            modelBuilder.Entity("IotApi.Models.SysUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<long?>("Creator")
                        .HasColumnType("bigint")
                        .HasColumnName("creator");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("SuperAdmin")
                        .HasColumnType("integer")
                        .HasColumnName("super_admin");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long?>("Updater")
                        .HasColumnType("bigint")
                        .HasColumnName("updater");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("sys_user");
                });

            modelBuilder.Entity("IotApi.Models.SysUserToken", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("sys_user_token");
                });
#pragma warning restore 612, 618
        }
    }
}
